services:
  predictor:
    build:
      context: .
      args:
        BASE_IMAGE: python:3.13-slim
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    networks:
      - app-shared-network

networks:
  app-shared-network:
    driver: bridge
    name: app-shared-network
